services:
  mysql:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ctf
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3307:3306
    restart: always
  ctfdefoumalade:
    image: htamarin/ctfdefoumalade
    build: . 
    ports:
      - 8000:3000
    restart: always
